---
- hosts: all
  connection: local
  vars_files:
    - vars/main.yaml

  roles:
    - name: roles/azure-auth
    - name: roles/infra-create
    - name: roles/cluster-create
    - name: roles/jumphost-create
      when:
        - azr_jumphost | bool
    - name: roles/egress-lockdown
      when:
        - azr_aro_egress_lockdown | bool
    - name: roles/wait-for-cluster
    # rerun infra-create as we need to update routes for egress lockdown
    - name: roles/infra-create
      when:
        - azr_aro_egress_lockdown | bool
    - name: roles/add-pull-secret
      when:
        - azr_aro_pull_secret != ""
        - azr_aro_public_api | bool
    - name: roles/finish

