---
- name: Create ARO cluster
  hosts: all
  connection: local
  vars_files:
    - vars/main.yaml

  roles:
    - role: infra-create
    - role: cluster-create
    - role: jumphost-create
      when:
        - azr_jumphost | bool
    - role: egress-lockdown
      when:
        - azr_aro_egress_lockdown | bool
    - role: wait-for-cluster
    # rerun infra-create as we need to update routes for egress lockdown
    - role: infra-create
      when:
        - azr_aro_egress_lockdown | bool
    - role: add-pull-secret
      when:
        - azr_aro_pull_secret != ""
        - azr_aro_public_api | bool
    - role: finish
