---
# tasks file for roles/jumphost-create

# azr_jumphost: true
# azr_jumphost_ssh_key: ~/.ssh/id_rsa
# azr_jumphost_subnet:
#   name: jumphost
#   address_prefix_cidr: "10.0.3.0/24"

- name: "Create a jumphost subnet (non egress lockdown)"
  azure_rm_subnet:
    resource_group: "{{ azr_resource_group }}"
    virtual_network_name: "{{ azr_virtual_network.name }}"
    name: "{{ azr_jumphost_subnet.name }}"
    address_prefix_cidr: "{{ azr_jumphost_subnet.address_prefix_cidr }}"

- name: Create VM with defaults
  azure_rm_virtualmachine:
    resource_group: "{{ azr_resource_group }}"
    name: jumphost
    admin_username: aro
    ssh_password_enabled: false
    ssh_public_keys:
      - path: "/home/aro/.ssh/authorized_keys"
        key_data: "{{ lookup('file',azr_jumphost_ssh_key) }}"
    subnet_name: "{{ azr_jumphost_subnet.name }}"
    vm_size: Standard_DS2_v2
    image:
      offer: "RHEL"
      publisher: "RedHat"
      version: "latest"
      sku: "8.2"
    custom_data: "{{ lookup('file', 'user_data.sh') }}"
  register: _jumphost

# - debug:
#     var: _jumphost


# - name: make sure we have a subnet to use
#   set_fact:
#     jumphost_subnet_id: "{{ _public_subnet_ids[0] }}"
#   when: jumphost_subnet_id is not defined

# - name: create ssh key pair
#   ec2_key:
#     name: "ROSA-{{ cluster_name }}-jumphost"
#     key_material: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

# - name: create ssh security group
#   ec2_group:
#     name: "ROSA-{{ cluster_name }}-jumphost-ssh"
#     description: security group for SSH
#     vpc_id: "{{ vpc_id }}"
#     # region: "{{ region | default('us-east-2') }}"
#     rules:
#       - proto: tcp
#         ports:
#         - 22
#         cidr_ip: 0.0.0.0/0
#         rule_desc: allow ssh
#       - proto: tcp
#         ports:
#         - 8080
#         cidr_ip: 10.0.0.0/8
#         rule_desc: allow proxy
# - name: start jumphost instance
#   ec2_instance:
#     name: "ROSA-{{ cluster_name }}-jumphost"
#     key_name: "ROSA-{{ cluster_name }}-jumphost"
#     vpc_subnet_id: "{{ jumphost_subnet_id }}"
#     instance_type: "{{ jumphost_instance_type }}"
#     security_group: "ROSA-{{ cluster_name }}-jumphost-ssh"
#     user_data: "{{ lookup('file', 'user_data.sh') }}"
#     network:
#       assign_public_ip: true
#     image_id: "{{ jumphost_ami }}"
#     tags:
#       Name: "ROSA-{{ cluster_name }}-jumphost"

